name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: 📚 Main
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0

      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: pnpm

      - name: 📦 Install deps (with cache)
        run: pnpm install

      - name: 👀 Lint
        run: pnpm lint

      - name: 🚀 Build
        run: pnpm build
        env:
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}